// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efswlnvdpjcoahbmqjky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmc3dsbnZkcGpjb2FoYm1xamt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzI1NzksImV4cCI6MjA3MTAwODU3OX0.qgnhkpKYI6EaFZ2O4YzGD0GuwFKIe3ojXYLCbquBuZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});